name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yaml \
            --stack-name text-to-sql-chatbot \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              SecretName=text-to-sql-chatbot-secrets
      
      - name: Get deployment outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name text-to-sql-chatbot \
            --query "Stacks[0].Outputs" \
            --output table
